### ISSUE TITLE
Any Deploy for VPS

### ISSUE THREAD

**Issue by PitchAbyss** [LISA-KOREA/UPLOADER-BOT-V4#17]
i have my personal server can i deploy this ? also any other way to keep bot running other then metioned https://uptimerobot.com/

please reply thanks

**Comment by AshutoshGoswami24** [comment]
ah which vps bro dm me https://t.me/X_dm_me

**Comment by AshutoshGoswami24** [comment]
i thing just run `pip install -r requirements.txt` `python3 bot.py`

**Comment by PitchAbyss** [comment]
Dm'd u brother

**Comment by LISA-KOREA** [comment]
Clone the repo

**Comment by LISA-KOREA** [comment]
Add cd repo name

**Comment by PitchAbyss** [comment]
> Add cd repo name

Share commands to start bot and setup config please

**Comment by AshutoshGoswami24** [comment]
bro he need renaem bot to just add thambnail

**Comment by LISA-KOREA** [comment]
I don’t have rename bot
